### ISSUE TITLE
External code invocation

### ISSUE THREAD

**Issue by igaray** [lambdaclass/cairo_sierra2mlir#13]
It will eventually be necessary to call functions implemented in rust from the emitted programs.
Research which mechanism allows this, and lay down the framework needed.

**Comment by edg-l** [comment]
It is definitly possible, although the functions defined within rust will need to use the C calling convention most probably. A.k.a. `extern "C"`

Although we need a way to let the compiler know about these, so the function is declared with external linking. This probs should be added at the cairo level (?), and thus sierra.

**Comment by azteca1998** [comment]
Implemented in the auxiliary library `sierra2mlir-utils`.
