### ISSUE TITLE
Libfunc: gas

### ISSUE THREAD

**Issue by igaray** [lambdaclass/cairo_sierra2mlir#66]
- Compiler internals:
  - [x] Gas global variable
  - [x] Gas global variable manipulation (increase, decrease, get) 
- Libfuncs:
  - [x] withdraw_gas
  - [x] withdraw_gas_all
  - [x] get_available_gas
  - [x] get_builtin_costs

Some documentation references: 

- [ StarkWare Sessions 23 | Sierra - Enforcing Safety Using Typesystems | Shahar Papini ](https://www.youtube.com/watch?v=-EHwaQuPuAA)
- [ StarkWare Sessions 23 | Not Stopping at the Halting Problem | Ori Ziv ](https://www.youtube.com/watch?v=wYxUedcdVZ4&list=PLcIyXLwiPilV7OFs_bkGe1-qqE3Y4QiEl&index=17)
- [StarkNet Documentation: Fee Mechanism](https://docs.starknet.io/documentation/architecture_and_concepts/Fees/fee-mechanism/)

> Note: Cairo prevents us from running program with infinite loops by including a gas meter. The gas meter is a mechanism that limits the amount of computation that can be done in a program. By setting a value to the --available-gas flag, we can set the maximum amount of gas available to the program. Gas is a unit of measurementsthat expresses the computation cost of an instruction. When the gas meter runs out, the program will stop. In this case, the program panicked because it ran out of gas, as the stop condition was never reached. It is particularly important in the context of smart contracts deployed on Starknet, as it prevents from running infinite loops on the network. If you're writing a program that needs to run a loop, you will need to execute it with the --available-gas flag set to a value that is large enough to run the program.

- [src](https://cairo-book.github.io/ch02-05-control-flow.html?highlight=gas#repeating-code-with-loop)
- [withdraw gas example](https://cairo-book.github.io/ch05-01-enums.html?highlight=gas#the-option-enum-and-its-advantages)

> As recursive functions can be a source of infinite loops if the stop condition is never met, the Cairo-to-Sierra compiler will inject a withdraw_gas method at the beginning of recursive functions. As this feature has not yet been implemented, developers are still expected to call withdraw_gas in recursive functions and handle the result themselves, although it should be included in a future release of the compiler.
> This withdraw_gas function will deduct the amount of gas required to run the function from the total gas available for the transaction by evaluating the cost of running each instruction in the function. The cost is analyzed by determining how many steps each operation takes - which is known at compile time for most operations. During the execution of a Cairo program, if the withdraw_gas call returns a null or negative value, the current function execution will stop, all pending variables will be consumed by calling dict_squash on unsquashed dictionaries and calling drop on other variables, and the execution will be considered as failed. Because all transactions on Starknet have a limited amount of spendable gas to execute the transactions, infinite loops are avoided - and by ensuring that enough gas is still available to drop the variables and stop the execution, the sequencer will be able to collect the fees from the transaction failure.

- [src](https://medium.com/nethermind-eth/under-the-hood-of-cairo-1-0-exploring-sierra-7f32808421f5)

> The branch_align libfunc is used to equalize gas costs and ap changes across merging paths of branching code.

- [src](https://medium.com/nethermind-eth/under-the-hood-of-cairo-1-0-exploring-sierra-9355d618b26f)

Code:
- [Sierra extension module: gas](https://github.com/starkware-libs/cairo/blob/main/crates/cairo-lang-sierra/src/extensions/modules/gas.rs)
- [Sierra gas computation crate](https://github.com/starkware-libs/cairo/tree/main/crates/cairo-lang-sierra-gas/src)
-[Sierra to casm gas invocation implementation](https://github.com/starkware-libs/cairo/blob/main/crates/cairo-lang-sierra-to-casm/src/invocations/gas.rs)

**Comment by edg-l** [comment]
https://github.com/starkware-libs/cairo/blob/main/crates/cairo-lang-runner/src/lib.rs#L407-L435

**Comment by edg-l** [comment]
Status: After #140 is merged, there will only be redeposit_gas missing, but we still need to found other places where the gas is deducted, so it matches cairo-run.

**Comment by edg-l** [comment]
Status: Gas matches, redeposit_gas will be implemented with the dict
